FROM alpine:3.4
MAINTAINER Teruyuki Kobayashi <koba1014@gmail.com>

ENV HUGO_VERSION 0.17
ENV HUGO_BINARY hugo_${HUGO_VERSION}_Linux-64bit

RUN apk update && apk upgrade && apk add --no-cache py-pygments git bash curl openssh-client

ADD https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}.tar.gz /tmp/

# RUN tar -xvzf /tmp/${HUGO_BINARY}.tar.gz -C /tmp/ && mv /tmp/hugo /usr/bin/hugo && rm -rf /tmp/*

# RUN tar -xvzf /tmp/${HUGO_BINARY}.tar.gz -C /tmp/ && mv /tmp/hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 /usr/bin/hugo && rm -rf /tmp/*
